### ISSUE TITLE
Allow users to view/edit their article(s) only

### ISSUE THREAD

**Issue by xxAnDrej-Bxx** [alex7r/overrideany#1]
Hello Alex,

I'm following up on the conversation we started at Stackexchange-[https://joomla.stackexchange.com/questions/20566/how-to-allow-users-to-view-edit-their-articles-only-joomla-3](url)

First of all, thanks for your help and your suggestions - I checked your plugin and the Readme file. I followed your instructions, made the necessary amendemets and installed the plugin. 
I need the plugin to work on the FRONT END, so I changed the following lines in the **overrideany.php** file:
```
$overridables['ContentModelCategory']['initial'] = JPATH_ROOT
            . '/components/com_content/models/category.php';
        $overridables['ContentModelCategory']['target']  = JPATH_ROOT
            . '/templates/g5_hydrogen/html/com_content/models/category.php';
```

Here's the code from my **target file**:

```
<?php
class ContentModelCategory extends ContentModelCategoryBase
{
	protected function getListQuery(){
  $db = JFactory::getDbo();
  $query = parent::getListQuesry();

  $group_B = 8;
  if(!in_array($group_B,JFactory::getUser()->getAuthorisedGroups())){
      $query->where($db->qn('created_by').' = '.$db->q(JFactory::getUser()->id));
  }
  return $query;
}
}
```
I used the **getListQuery() function**  you suggested on Stackexchange. I just changed the nr. 11 to 8.

Here's my Q:
If I understand the function correctly, the function checks whether or not the logged in user is part of **group_B** and **group_B's ID** is **8** - is it correct or am I totally wrong here? :)

Based on my assumption above, only the users of the group with the ID nr. 8 (in my case the **Super Users** group) should see all articles. But when I tried to log in as an user of the **Author** user group (in my case ID nr. 3) I can see all articles posted by users from different groups as well.

Any Ideas how to solve this please?

Thanks.

**Comment by alex7r** [comment]
Seems like Joomla uses JLoader::register with force option, I've fixed this in latest commits
Code for your file would be:
```PHP
class ContentModelArticles extends ContentModelArticlesBase
{
    protected function getListQuery(){
        $db = JFactory::getDbo();
        $query = parent::getListQuery();

        /*
         * $group that can see all the posts
         */
        $group = 10;
        if(!in_array($group,JFactory::getUser()->getAuthorisedGroups())){
            $query->where($db->qn('created_by').' = '.$db->q(JFactory::getUser()->id));
        }
        return $query;
    }
}
```
Check that model I suggest you to use is `ContentModelArticles`
As it's used for articles, category, featured views.
And I'd like to mention that with scheme:
```
- Authors
-- Authors Supervisers
```
`Authors Supervisers` will be a part of a group `Authors`.
So users that must not have access to others post should be as high as it gets in leader.

**Comment by xxAnDrej-Bxx** [comment]
Hello @alex7r ,

thanks for taking the time and checking out my issue.

Everything works now as it should 👍  - I just changed the group variable's value to   `$group = 5`. 5 = ID of the group which can see all the posts.

1 additional Q:
How should the code look like, if the users from both **group ID#5** and **group ID#8** (my Super Users group) should be able see all the posts? I tried `$group = (5 || 8);` but that didn't work.
- This is really just a nice-to-have addition and maybe something that I can share on stackexchange for similar PHP-noobs as myself :)

**Comment by alex7r** [comment]
First thing that comes to my mind is having different checks and to variables.
May be you can invent something more beautiful, but quick working solution would be:
```PHP
if(!in_array($group1,JFactory::getUser()->getAuthorisedGroups()) && !in_array($group2,JFactory::getUser()->getAuthorisedGroups())){

}
```

**Comment by xxAnDrej-Bxx** [comment]
Thanks, the above condition works 👍 

We can close this issue now.

Can you update the code on the [initial stackexchange question](https://joomla.stackexchange.com/questions/20566/how-to-allow-users-to-view-edit-their-articles-only-joomla-3) as well please, so I can mark it as solved?

Thanks again for all the help 💯
